---
title: "Homework 7"
author: "Jacob Carey"
date: \today
header-includes:
    - \usepackage{amsthm}
    - \usepackage{mathtools}
output: pdf_document
---

```{r libs, echo=FALSE}
library(ggplot2)
```

1.

2.
    (i)
        The second derivative of $e^x$ is $e^x$, which is positive on the interval $(-\infty, \infty)$ and is thus convex.
        ```{r p2-i}
        x <- seq(-10, 10, by=0.1)
        qplot(x, exp(x), geom="line")
        ```

    (ii)
        The second derivative of $x^2$ is $2$, which is positive on the interval $(-\infty, \infty)$ and is thus convex.
        ```{r p2-ii}
        qplot(x, x^2, geom="line")
        ```

    (iii)
        The second derivative of $\ln x$ is $-\frac{1}{x^2}$, which is not postive on the interval $(-\infty, \infty)$ and is thus not convex.
        ```{r p2-iii}
        x <- seq(0, 10, by=0.1)
        qplot(x, log(x), geom="line")
        ```

3.

4.
    ```{r p4}
    x <- seq(-0.99, 1.99, by=0.01)
    g_x <- (1 + x) * log(1 + x)
    R_x <- (x ^ 2) / (2 * (1 + x / 3))
    data <- rbind(data.frame(x=x, y=g_x, label="g(x)"),
                  data.frame(x=x, y=x+R_x, label="x+R(x)"))
    ggplot(data, aes(x=x, y=y)) +
        geom_line(aes(colour=label, linetype=label))
    ```
    This is a pretty good approximation

5.
