---
title: "Homework 8"
author: "Jacob Carey"
date: \today
header-includes:
    - \usepackage{amsthm}
    - \usepackage{mathtools}
output: pdf_document
---

```{r libs, echo=FALSE}
library(ggplot2)
theme_set(theme_classic())
set.seed(1)
knitr::opts_chunk$set(message=FALSE)
```

1. Here I show a running mean of draws from a specified distribution to show that the sample average converges in distribution to the expected value.
```{r p1}
# number of draws
trials <- 1e3
x <- 1:trials

# normal
normal <- rnorm(trials, mean=5, sd=1)
qplot(x=x, y=cumsum(normal) / x, main="Normal(5, 1)") +
    geom_hline(yintercept=5)

# bernoulli
bernoulli <- rbinom(trials, 1, 0.4)
qplot(x=x, y=cumsum(bernoulli) / x, main="Bernoulli(0.4)") +
    geom_hline(yintercept=0.4)

# poisson
poisson <- rpois(trials, 5)
qplot(x=x, y=cumsum(poisson) / x, main="Poisson(5)") +
    geom_hline(yintercept=5)
```

2.
```{r p2}
# normal
normal <- matrix(rnorm(100 * trials, 5, 1), ncol=trials)
g <- sqrt(100) * (colMeans(normal) - 5) / 1
qplot(g, geom="blank") + 
    geom_histogram(aes(y=..density..)) +
    stat_function(fun=dnorm, args=list(mean=0, sd=1), colour="blue")

# bernoulli
bernoulli <- matrix(rbinom(100 * trials, 1, 0.4), ncol=trials)
g <- sqrt(100) * (colMeans(bernoulli) - 0.4) / sqrt(0.4 * 0.6)
qplot(g, geom="blank") + 
    geom_histogram(aes(y=..density..)) +
    stat_function(fun=dnorm, args=list(mean=0, sd=1), colour="blue")

# poisson
poisson <- matrix(rpois(100 * trials, 5), ncol=trials)
g <- sqrt(100) * (colMeans(poisson) - 5) / sqrt(5)
qplot(g, geom="blank") + 
    geom_histogram(aes(y=..density..)) +
    stat_function(fun=dnorm, args=list(mean=0, sd=1), colour="blue")
```

3. Since $x_n=o(a_n)$ then for all $\epsilon > 0$ there exists $N_1(\epsilon)$ such that if $n \geq N_1(\epsilon) \implies |x_n| < \frac{\epsilon}{K}|a_n|$. Similarly, for $y_n=O(b_n)$ there exists $K>0$ and $N_2(K)$ such that if $n > N_2(K) \implies |y_n| < K|b_n|$. Then 
    $$
    n > \max(N_1, N_2) \implies
    |x_n||y_n|=|x_n y_n| < \frac{\epsilon}{K}|a_n|K|b_n|=\epsilon|a_nb_n|
    $$
    Thus, $x_ny_n=o(a_nb_n)$.

4.
